@startuml
title Activity Diagram - Login Admin

partition "Admin" {
    start
    :Buka Sistem;
    :Masukkan Username & Password;
    :Kirim Data Login;
    stop
}

partition "Backend (Autentikasi)" {
    start
    :Validasi Akun;
    if (Login Valid?) then (Ya)
        :Akses Diberikan;
        stop
    else (Tidak)
        :Tolak Akses;
        :Tampilkan Pesan Gagal Login;
        stop
    endif
}

@startuml
title Activity Diagram - Menambah Data Beasiswa

partition "Admin" {
    start
    :Akses Menu Data Beasiswa;
    :Tambah Data Beasiswa;
    :Kirim Perubahan ke Backend;
    stop
}

partition "Backend (Proses Data Beasiswa)" {
    start
    :Terima Data;
    :Validasi & Simpan Perubahan;
    :Kirim Notifikasi Berhasil ke Admin;
    stop
}
@enduml

@startuml
title Activity Diagram - Mengedit Data Beasiswa

partition "Admin" {
    start
    :Akses Menu Data Beasiswa;
    :Edit Data Beasiswa;
    :Kirim Perubahan ke Backend;
    stop
}

partition "Backend (Proses Data Beasiswa)" {
    start
    :Terima Data;
    :Validasi & Simpan Perubahan;
    :Kirim Notifikasi Berhasil ke Admin;
    stop
}
@enduml

@startuml
title Activity Diagram - Menghapus Data Beasiswa

partition "Admin" {
    start
    :Akses Menu Data Beasiswa;
    :Hapus Data Beasiswa;
    :Kirim Perubahan ke Backend;
    stop
}

partition "Backend (Proses Data Beasiswa)" {
    start
    :Terima Data;
    :Validasi & Simpan Perubahan;
    :Kirim Notifikasi Berhasil ke Admin;
    stop
}
@enduml

@startuml
title Activity Diagram - Logout Admin

partition "Admin" {
    start
    :Klik Logout;
    stop
}

partition "System" {
    start
    :Hapus Session & Akses;
    :Kembali ke Halaman Login;
    stop
}
@enduml

@startuml
title Activity Diagram - Melihat Data Beasiswa

partition "Admin" {
    start
    :Melihat Data Beasiswa;
    stop
}

partition "Backend (Proses Membaca)" {
    start
    :Menampilkan Data;
    stop
}
@enduml

@startuml
title Activity Diagram - Melihat Data Beasiswa

partition "Mahasiswa" {
    start
    :Melihat Data Beasiswa;
    stop
}

partition "Backend (Proses Membaca)" {
    start
    :Menampilkan Data;
    stop
}
@enduml

@startuml
title Activity Diagram - Melihat Data Beasiswa

partition "Mahasiswa" {
    start
    :Search Data Beasiswa;
    stop
}

partition "Backend (Proses Membaca)" {
    start
    :Menampilkan Data;
    stop
}
@enduml

@startuml
title Activity Diagram - Melihat Data Beasiswa

partition "Admin" {
    start
    :Search Data Beasiswa;
    stop
}

partition "Backend (Proses Membaca)" {
    start
    :Menampilkan Data;
    stop
}
@enduml