@startuml

package "UserManagement" {

    class Admin {
        - id: int
        - username: string
        - password: string
        + login()
        + logout()
        + TambahBeasiswa()
        + EditBeasiswa()
        + HapusBeasiswa()
    }

    class Mahasiswa {
        - id: int
        - username: string
        + LihatBeasiswa()
    }

}

package "Beasiswa" {

    class Beasiswa {
        - id: int
        - nama: string
        - sumber: string
        - syarat: string
        - deskripsi: string
        - jenis: string
    }
}

Admin --> Beasiswa : mengelola 

Mahasiswa --> Beasiswa : melihat 

@enduml