@startuml
title ERD Sistem Informasi Beasiswa

entity Jenjang {
  +id_jenjang : INT <<PK>>
  nama_jenjang : VARCHAR(10)
}

entity Kategori {
  +id_kategori : INT <<PK>>
  nama_kategori : VARCHAR(30)
}

entity Admin {
  +IDAdmin : CHAR(9) <<PK>>
  username : VARCHAR(24)
  email : VARCHAR(40)
  password : VARCHAR(24)
}

entity Beasiswa {
  +id_beasiswa : INT <<PK>>
  nama_beasiswa : VARCHAR(100)
  tgl_buka : DATE
  tgl_tutup : DATE
  link_beasiswa : VARCHAR(500)
  deskripsi : VARCHAR(MAX)
  nama_jenjang : VARCHAR(10) <<FK>>
  nama_kategori : VARCHAR(30) <<FK>>
}

Jenjang "1" -- "0..N" Beasiswa : memiliki
Kategori "1" -- "0..N" Beasiswa : mengelompokkan

@enduml