@startuml
title ERD Sistem Informasi Beasiswa

entity Jenjang {
  +id_jenjang : INT <<PK>>
  nama_jenjang : VARCHAR(10)
}

entity Kategori {
  +id_kategori : INT <<PK>>
  nama_kategori : VARCHAR(30)
}

entity Admin {
  +nidn : VARCHAR(20) <<PK>>
  username : VARCHAR(24)
  email : VARCHAR(40)
  password : VARCHAR(24)
  nama_lengkap : VARCHAR(60)
}

entity Beasiswa {
  +id_beasiswa : INT <<PK>>
  nama_beasiswa : VARCHAR(100)
  tgl_buka : DATE
  tgl_tutup : DATE
  link_beasiswa : VARCHAR(500)
  deskripsi : VARCHAR(MAX)
  id_jenjang : INT <<FK>>
  id_kategori : INT <<FK>>
}

Jenjang "1" -- "0..N" Beasiswa : memiliki
Kategori "1" -- "0..N" Beasiswa : mengelompokkan

@enduml