@startuml
title Use Case Diagram - Layanan Informasi Beasiswa
left to right direction

actor Admin #LightPink
actor User #Darkorange

rectangle "Layanan Informasi Beasiswa" {
    usecase "Login" as UC0 #LightBlue
    usecase "Logout" as UC1 #LightBlue
    'usecase "Registrasi" as UC2 #LightBlue

    'usecase "Melakukan\nPemesanan" as UC3 #LightGreen
    'usecase "Mencetak\nStruk" as UC4 #LightGreen
    usecase "Melihat Daftar Beasiswa" as UC5 #LightGreen
    usecase "Search Beasiswa" as UC6 #LightGreen
    'usecase "Mengelola Data Diri (Profil)" as UC7 #LightGreen

    usecase "Mengedit Informasi\nBeasiswa" as UC8 #LightCoral
    usecase "Menambah Informasi\nBeasiswa" as UC9 #LightCoral
    usecase "Menghapus Informasi\nBeasiswa" as UC10 #LightCoral
}
    
UC0 .> UC1 : <<extend>>
'UC2 ..>UC0 : <<include>>
UC0 ..>UC9 : <<extend>>
UC0 ..>UC10 : <<extend>>
UC0 ..>UC8 : <<extend>>
'UC9 ..>UC4 : <<extend>>
'UC0 ..>UC3 : <<extend>>
'UC3 ..>UC6 : <<extend>>
'UC0 ..>UC7 : <<extend>>
'UC3 ..> UC4 : <<extend>>

Admin -->UC5
Admin -->UC0
Admin-->UC6
User-->UC5
User-->UC6
@enduml